# Workshops

```{r share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

```{r style-share-again, echo=FALSE}
xaringanExtra::style_share_again(
  share_buttons = c("twitter", "linkedin", "pocket")
)
```


## Linear multilevel models (LMM) workshop (9th Sept 2022)

Either click on the links or click on the embedded slides and press 'F' to go full screen. Advance through slides with arrow keys, and press 'O' for an overview of all slides.

**Part 1** ([link](https://mlisi.xyz/files/workshops/LMM101/LMM_part1.html))

```{r, echo=FALSE}
xaringanExtra::embed_xaringan(
  url = "https://mlisi.xyz/files/workshops/LMM101/LMM_part1.html",
  ratio = "16:9"
)

```

**Part 2** ([link](https://mlisi.xyz/files/workshops/LMM101/LMM_part2.html))

```{r, echo=FALSE}
xaringanExtra::embed_xaringan(
  url = "https://mlisi.xyz/files/workshops/LMM101/LMM_part2.html",
  ratio = "16:9"
)
```

**Practicals**

[Exercises with solution (link)](https://mlisi.xyz/files/workshops/LMM101/exercises/exercises_questions.html)